import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

    javaSidebar: [
    {
      type: "category",
      label: "Java基础",
      items: [
        "Java/基础/Java概述",
        "Java/基础/Java安装—Win10",
        "Java/基础/Java安装—Linux",
        "Java/基础/Java入门程序",
        "Java/基础/Java注释",
        "Java/基础/Java变量与标识符",
        "Java/基础/Java基本数据类型",
        "Java/基础/Java运算符",
        "Java/基础/Java流程控制",
        "Java/基础/Java数组",
      ],
    },
   
  ],

  springSidebar: [
    {
      type: "category",
      label: "Spring",
      items: [
        "Spring/Spring/Spring概述",
        "Spring/Spring/SpringIOC-XML",
        "Spring/Spring/SpringIOC注解",
        "Spring/Spring/SpringAOP概述",
        "Spring/Spring/SpringAOP",
        "Spring/Spring/Spring事务管理",
      ],
    },
    {
      type: "category",
      label: "SpringMVC",
      items: [
        "Spring/SpringMVC/SpringMVC入门",
        "Spring/SpringMVC/SpringMVCRESTful",
        "Spring/SpringMVC/SpringMVC执行流程",
        "Spring/SpringMVC/SpringMVC组件解析",
        "Spring/SpringMVC/SpringMVCDispatcherServlet",
        "Spring/SpringMVC/SpringMVC请求",
        "Spring/SpringMVC/SpringMVC响应",
      ],
    },
  ],

  gitSidebar: [
    {
      type: "category",
      label: "Git",
      items: ["Git/Git基础命令", "Git/Git分支", "Git/Git远程仓库"],
    },
  ],

  linuxSidebar: [
    {
      type: "category",
      label: "Linux",
      items: [
        "Linux/Linux目录结构",
        "Linux/Linux常用命令",
        "Linux/Linux vi和vim编辑器",
        "Linux/Linux用户管理",
        "Linux/Linux组管理",
        "Linux/Linux权限管理",
        "Linux/Linux任务调度",
        "Linux/Linux磁盘管理",
        "Linux/Linux网络配置",
      ],
    },
  ],
};

export default sidebars;
